apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/praveeneswarM/Fitness_Tracker
    targetRevision: main
    path: helm
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://kubernetes.default.svc
    namespace: praveen-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
 